### PR TITLE
feat: add `ppx_decimal` for decimal literals

### PR DESCRIPTION
**Pull request by zbaylin**
This is similar to [zarith-ppx](https://github.com/Drup/zarith-ppx). The ppx transforms integer and "float" literals suffixed with `r` into `Decimal.of_string x`, i.e.

```ocaml
# let () = print_endline @@ Decimal.to_string 10.1m
10.1
```

~~The suffix `'r'` is used since `d` is disallowed due to its use in hexadecimal numbers (how would one parse `0x123d`?). The "r" is for either "real" or "rational", but I'm open to other ideas if anyone has any.~~

The suffix has been changed to `m` for consistency with other languages.

### CODE REVIEW

**Comment by yawaramin** [comment]
Cool! Can we use the `m` suffix like C# does? https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types#real-literals

**Comment by anmonteiro** [comment]
FWIW Clojure also uses M https://clojuredocs.org/clojure.core/bigdec

**Comment by anmonteiro** [comment]
Another nit: ppxes in opam tend to be called `ppx_*` with an underscore. Not sure if we want to abide by that (implicit) convention

**Comment by yawaramin** [comment]
Ah, I would also want to stick with this convention.

**Comment by zbaylin** [comment]
Thanks for the feedback -- incorporated both of those changes.

**Review by yawaramin — APPROVED** [review]

**Pull request merged**
