### PR TITLE
fix: set exponent to `0` in `of_float` when argument is integral

### LINKED ISSUE #12: `of_float f` returns `f * 10` when `f % 1. = 0.`
Sorry for the confusing title, but when converting a float to a Decimal, it seems as if we're scaling the number by 10 if it's an integer (i.e. $\mathrm{rem}(f, 1.0) = 0.0$).

The culprit seems to be this line:
https://github.com/yawaramin/ocaml-decimal/blob/c5ef815bd81508c57af40b98f759353b060c0abe/lib/decimal.ml#L423

If there is nothing on the right side of the decimal point (i.e. it is an integer), we set the exponent to 1, but I think it should be 0? If we have `100.`, this becomes `"100", ""`, which should be $100 \times 10^0$ but we have $100 \times 10 ^ 1 = 1000$.

Luckily this is an easy fix if it is indeed the issue.

### PR DESCRIPTION
**Pull request by zbaylin**
Resolves #12

### CODE REVIEW

**Comment by anmonteiro** [comment]
can you add a test for this?

**Comment by yawaramin** [comment]
Thanks! And yes please it would be good to have a test.

**Comment by yawaramin** [comment]
Actually, I'm now wondering why I even bothered to implement this with its own logic instead of just defining

```ocaml
let of_float ?context value =
  Decimal.of_string ?context (string_of_float value)
```

I'm pretty sure this would also eliminate precision loss as the conversion would be going through a string.

**Comment by zbaylin** [comment]
> Actually, I'm now wondering why I even bothered to implement this with its own logic instead of just defining
> 
> ```ocaml
> let of_float ?context value =
>   Decimal.of_string ?context (string_of_float value)
> ```
> 
> I'm pretty sure this would also eliminate precision loss as the conversion would be going through a string.

The current solution should be faster since the float is guaranteed to already be a valid decimal string. Actually, the more I think about this the more I wonder if it's true since [`string_of_float` can return scientific notation](https://try.ocamlpro.com/#code/let'()'='print_endline'@@'string_of_float'0.000001). I'm not sure I follow how the precision loss would be different, but I'm probably just missing something.

I was looking into how pydecimal does their tests for this. It seems like they use the `random.expovariate` function which I don't think we have an analogue for in OCaml (at least in `Stdlib.Random`), but there are some other hard-coded cases I can port over:
https://github.com/python/cpython/blob/9ff7b4af137b8028b04b52addf003c4b0607113b/Lib/test/test_decimal.py#L692-L713

**Comment by yawaramin** [comment]
If we directly use `Decimal.of_string`, then we piggy-back on all the tests that are already using it. The speed difference is a consideration, but does it override the benefits of simplicity and maintainability of the implementation?

Re: the precision loss, yeah on thinking about it more, that's probably not a concern even now.

**Comment by zbaylin** [comment]
To be honest the implementation of `of_float` is short enough that I think it should be easy enough to see what's going on to root out bugs. I definitely understand if you want to change it though. Regardless, I've added some tests from the pydecimal distribution which are passing. Let me know if those work for you.

**Review by yawaramin — APPROVED** [review]

**Comment by yawaramin** [comment]
Well, already-written code wins in my book 🙂 Thanks!

**Pull request merged**
